[FIX] Moved merging check from purchase order level to line level.
avoinsystems/account-analytic pull request #1
Opened 2019-01-15 09:32 UTC by n17

- Link to issue: https://repo.web-veistamo.fi/odoo/xpansa/tietokeskus/issues/14

2019-01-15 11:10 UTC, aisopuro requested changes
Just a few quibbles, nothing major.

2019-01-15 11:10 UTC, aisopuro commented on procurement_mto_analytic/models/procurement.py
> +        res = super(ProcurementRule, self). \
Unnecessary whitespace.

2019-01-15 11:10 UTC, aisopuro commented on procurement_mto_analytic/models/purchase_order_line.py
> +        """ This function purpose is to be override with the purpose to forbide _run_buy  method
This comment could describe what this extension does.
> Do not merge into a line with a different analytic account

2019-01-15 11:12 UTC, aisopuro commented
@n17 please "redirect" this PR to be merged into the main OCA repo. That way we can have it run CI checks for us as well.

2019-02-09 09:14 UTC, mlaitinen commented
Is this really supposed to target `11.0` of our own repository?

2019-02-14 08:49 UTC, n17 commented
> Is this really supposed to target `11.0` of our own repository?

@mlaitinen I think so. Do you think it should have been pushed directly to the OCA repository?

2019-02-14 08:58 UTC, mlaitinen commented
> > Is this really supposed to target `11.0` of our own repository?
> 
> @mlaitinen I think so. Do you think it should have been pushed directly to the OCA repository?

I mean, we try to keep the `x.0` branches clean and without any extra commits compared to `OCA/x.0`. So I think you either want to make a PR for `avoinsystems/11.0-avoinsystems` (which doesn't exist yet but can be created by forking `11.0`) or `OCA/11.0`. Right, @aisopuro ?

2019-02-14 09:55 UTC, aisopuro commented
Agreed @mlaitinen . `avoinsystems/*.0` should be identical to `OCA/*.0`

2019-02-28 15:46 UTC, n17 commented
The OCA pull request based on this was just merged. Can this PR be closed now?

2019-02-28 15:48 UTC, aisopuro commented
Yes.

2019-02-28 15:48 UTC, closed without merging